In [9]:
import numpy as np
import pickle
import pandas as pd

In [10]:
import pickle

ohe_sex = pickle.load(open('models/ohe_sex.pkl', 'rb'))
ohe_Embarked = pickle.load(open('models/ohe_Embarked.pkl', 'rb'))
si_age = pickle.load(open('models/si_age.pkl', 'rb'))
si_Embarked = pickle.load(open('models/si_Embarked.pkl', 'rb'))
Clf = pickle.load(open("models/Clf.pkl" , 'rb'))

In [11]:
# Pclass / Gender / age / sibSp / Parch / Fare / Embarked 
test_input = np.array([2 , 'male' , 31.0 , 0 ,0 ,10.5 , 'S'] , dtype=object) .reshape(1,7)

In [12]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [13]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\zaina\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [14]:
test_input_sex

array([[0., 1.]])

In [15]:
test_input_embark = ohe_Embarked.transform(test_input[:,-1].reshape(1,1))

In [16]:
test_input_age = test_input[:,2].reshape(1,1)

In [17]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embark) ,axis=1)

In [18]:
test_input_transformed.shape

(1, 10)

In [19]:
Clf.predict(test_input_transformed)

array([1])